version: '3.8'

services:
  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-api:latest
    container_name: chatbot-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge 